name: 'hello-world'
services:
  web:
    container_name: 'hello-world-example'
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./hello-world.html:/usr/share/nginx/html/index.html

